title: Juan Castagnini
description: Food Science and Technology
remote_theme: pages-themes/cayman@v0.2.0
permalink: /:categories/:title/
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap

social:
  twitter: https://x.com/jmcastagnini
  linkedin: https://www.linkedin.com/in/juanmanuelcastagnini/

lang: en